export function translateToUrdu(english: string): string {
  const phraseDictionary: Record<string, string> = {
  "never give up": "کبھی ہار نہ مانیں",
  "believe in yourself": "خود پر یقین رکھو",
  "hard work": "محنت",
  "stay positive": "مثبت رہو",
  "follow your dreams": "اپنے خوابوں کی پیروی کرو",
  "take the first step": "پہلا قدم اٹھاؤ",
  "keep moving forward": "آگے بڑھتے رہو",
  "don’t be afraid": "ڈرنا نہیں",
  "make it happen": "یہ ممکن بناؤ",
  "every step counts": "ہر قدم اہم ہے",
  "push your limits": "اپنی حدوں کو پار کرو",
  "focus on growth": "ترقی پر توجہ دو",
  "trust the process": "عمل پر یقین رکھو",
  "be the change": "تبدیلی خود بنو",
  "set your goals": "اپنے اہداف مقرر کرو",
  "nothing is impossible": "کچھ بھی ناممکن نہیں ہے",
  "small steps every day": "روزانہ چھوٹے قدم",
  "progress not perfection": "ترقی، نہ کہ کمال",
  "fall in love": "محبت میں پڑنا",
  "pick up": "اٹھانا",
  "dig deep": "گہرائی میں کھودنا",
  "keep going": "جاری رکھو",
  "write about": "لکھنا",
  "creep into": "چپکے سے داخل ہونا",
  "positive thinking": "مثبت سوچ",
  "love with care": "محبت سے خیال رکھنا",
   "slight dip": "معمولی کمی",
  "steady grip": "مضبوط گرفت",
  "search activity": "تلاش کی سرگرمی",
  "direct a firehose": "بہاؤ کو ہدایت دینا",
  "leads and commerce": "رہنمائی اور تجارت",
  "implemented ai overviews": "اے آئی جائزے نافذ کیے",
  "an evolution of": "کا ارتقاء",
  "ai summaries": "اے آئی خلاصے",
  "familiar list": "جانی پہچانی فہرست",
  "blue links": "نیلے روابط",
  "according to one study": "ایک مطالعے کے مطابق",
  "nearly 35 percent decline": "تقریباً 35 فیصد کمی",
  "outbound clicks": "باہر جانے والی کلکس",
  "search engine marketing": "سرچ انجن مارکیٹنگ",
  "joint launch": "مشترکہ آغاز",
  "learning science": "سائنس سیکھنے کا عمل",
  "ted series": "ٹی ای ڈی سیریز",
  "science press": "سائنس پریس",
  "cross-sector partnership": "بین الشعبہ شراکت داری",
  "new channel international education group": "نیو چینل بین الاقوامی تعلیمی گروپ",
  "chinese-language ted science video book series": "چینی زبان میں ٹی ای ڈی سائنس ویڈیو کتاب سیریز",
  "officially launched": "باقاعدہ طور پر شروع کیا گیا",
  "beijing international book fair": "بیجنگ بین الاقوامی کتاب میلہ",
  "china national convention center": "چائنا نیشنل کنونشن سینٹر",
  "interactive science education platform": "انٹرایکٹو سائنس تعلیم پلیٹ فارم",
  "research resources": "تحقیقی وسائل",
  "comprehensive solutions": "جامع حل",
  "regional science education": "علاقائی سائنس تعلیم",
  "related industries": "متعلقہ صنعتیں"
  };

  const wordDictionary: Record<string, string> = {
    "i": "میں", "you": "آپ", "we": "ہم", "they": "وہ", "he": "وہ", "she": "وہ", "it": "یہ",
    "is": "ہے", "are": "ہیں", "was": "تھا", "were": " تھے", "am": "ہوں",
    "do": "کرو", "did": "کیا", "does": "کرتا ہے", "have": "رکھنا", "has": "رکھتا ہے", "had": "رکھا تھا",
    "the": "دی", "a": "ایک", "an": "ایک", "and": "اور", "or": "یا", "not": "نہیں",
    "this": "یہ", "that": "وہ", "in": "میں", "on": "پر", "from": "سے", "to": "کو", "for": "کے لیے",
    "of": "کا", "with": "کے ساتھ", "as": "جیسے", "at": "پر", "by": "کے ذریعے",
    "will": "کرے گا", "can": "سکتا ہے", "should": "چاہیے", "must": "ضرور",
    "more": "زیادہ", "less": "کم", "very": "بہت", "all": "سب", "some": "کچھ", "any": "کوئی",
    "each": "ہر ایک", "who": "کون", "what": "کیا", "when": "کب", "where": "کہاں", "why": "کیوں", "how": "کیسے",
    "yes": "ہاں", "no": "نہیں", "please": "براہ کرم", "thank you": "شکریہ", "sorry": "معاف کیجیے",
    "hello": "ہیلو", "hi": "ہیلو", "goodbye": "الوداع", "welcome": "خوش آمدید",
    "happy": "خوش", "sad": "اداس", "angry": "غصے میں", "excited": "پرجوش", "bored": "بور",
    "tired": "تھکا ہوا", "hungry": "بھوک لگی", "thirsty": "پیاسا", "scared": "ڈر گیا",
    "good": "اچھا", "bad": "برا",
    "heart": "دل", "soul": "روح", "mind": "دماغ", "memory": "یاد", "pain": "درد",
  "beauty": "خوبصورتی", "hurt": "تکلیف دینا", "scratch": "خراش", "cross": "صلیب",
  "shatter": "چکناچور", "destroy": "تباہ", "art": "فن", "axe": "کلہاڑا",
  "pretense": "بناوٹ", "narrow": "تنگ", "passage": "راستہ", "tool": "اوزار",
  "mountain": "پہاڑ", "rock": "چٹان", "stone": "پتھر", "earth": "زمین",
  "ground": "زمین", "dirt": "مٹی", "sand": "ریت", "clay": "کیچڑ",
  "water": "پانی", "river": "دریا", "lake": "جھیل", "ocean": "سمندر", "sea": "سمندر",
  "sky": "آسمان", "cloud": "بادل", "sun": "سورج", "moon": "چاند", "star": "ستارہ",
  "fire": "آگ", "light": "روشنی", "darkness": "اندھیرا", "wind": "ہوا", "air": "ہوا",
  "life": "زندگی", "death": "موت", "birth": "پیدائش", "future": "مستقبل", "past": "ماضی",
  "present": "حال", "time": "وقت", "moment": "لمحہ", "day": "دن", "night": "رات",
  "year": "سال", "month": "مہینہ", "week": "ہفتہ", "hour": "گھنٹہ", "minute": "منٹ", "second": "سیکنڈ",
  "love": "محبت", "hate": "نفرت", "friend": "دوست", "enemy": "دشمن", "family": "خاندان",
  "home": "گھر", "house": "مکان", "room": "کمرہ", "door": "دروازہ", "window": "کھڑکی",
  "street": "گلی", "road": "سڑک", "city": "شہر", "town": "قصبہ", "village": "گاؤں",
  "country": "ملک", "world": "دنیا", "universe": "کائنات",
  "school": "اسکول", "teacher": "استاد", "student": "طالب علم", "class": "کلاس", "book": "کتاب",
  "pen": "قلم", "paper": "کاغذ", "notebook": "رجسٹر", "bag": "بیگ", "desk": "میز",
  "chair": "کرسی", "table": "میز", "computer": "کمپیوٹر", "phone": "فون", "internet": "انٹرنیٹ",
  "work": "کام", "job": "نوکری", "business": "کاروبار", "money": "پیسہ", "bank": "بینک",
  "market": "بازار", "store": "دکان", "shop": "دکان", "product": "مصنوعات", "service": "سروس",
  "food": "کھانا", "drink": "پینا", "fruit": "پھل", "vegetable": "سبزی", "meat": "گوشت",
  "bread": "روٹی", "rice": "چاول", "tea": "چائے", "coffee": "کافی",
  "health": "صحت", "medicine": "دوا", "doctor": "ڈاکٹر", "hospital": "ہسپتال", "nurse": "نرس",
  "exercise": "ورزش", "fitness": "فٹنس", "diet": "خوراک", "nutrition": "غذائیت",

  "someone": "کوئی", "their": "ان کا", "your": "آپ کا", "my": "میرا",
  "me": "مجھے", "might": "شاید", "because": "کیونکہ",
  "about": "کے بارے میں",
  "after": "بعد میں", "before": "پہلے", "every": "ہر",
   "today": "آج", "tomorrow": "کل", "yesterday": "گزشتہ روز",
    "man": "آدمی", "woman": "عورت", "boy": "لڑکا", "girl": "لڑکی", "child": "بچہ", "children": "بچے",

    "car": "گاڑی", "bus": "بس", "train": "ٹرین", "plane": "جہاز", "boat": "کشتی", "bike": "سائیکل",
    "eat": "کھانا", "sleep": "سونا", "wake": "جاگنا", "sit": "بیٹھنا", "stand": "کھڑا ہونا",
    "walk": "چلنا", "run": "دوڑنا", "jump": "چھلانگ لگانا", "talk": "بات کرنا", "listen": "سننا",
    "see": "دیکھنا", "look": "دیکھو", "watch": "مشاہدہ کرنا", "write": "لکھنا", "read": "پڑھنا",
    "play": "کھیلنا", "study": "مطالعہ کرنا", "learn": "سیکھنا", "teach": "سکھانا",
    "open": "کھولنا", "close": "بند کرنا", "start": "شروع کرنا", "stop": "روکنا", "help": "مدد کرنا",
    "clean": "صاف کرنا", "wash": "دھونا", "cook": "پکانا", "drive": "چلانا", "travel": "سفر کرنا",
    "buy": "خریدنا", "sell": "بیچنا", "pay": "ادائیگی کرنا", "give": "دینا", "take": "لینا",
    "like": "پسند کرنا", "need": "ضرورت ہونا", "want": "چاہنا",
    "fall": "گرنا",
  "creep": "چپکے سے آنا",
  "destroyed": "تباہ",
  "landslides": "زمین کھسکنا",
  "blocked": "روک دیا",
  "boulders": "چٹانیں",
  "pick": "اٹھانا",
  "shovel": "بیلچہ",
  "crafted": "تخلیق کیا",
  "mortar": "مٹی",
  "trap": "پھنسانا",
  "memories": "یادیں",
  "nail": "کیل",
  "words": "الفاظ",
  "sliver": "چوٹی",
  "precious": "قیمتی",
  "gem": "جواہر",
  "hiding": "چھپا ہوا",
  "mounds": "ڈھیر",
  "coal": "کوئلہ",
  "minds": "ذہن",
  "knowing": "جاننا",
  "beautiful": "خوبصورت",
  "damage": "نقصان پہنچانا",
  "dig": "کھودنا",
  "leave": "چھوڑ دینا",
  "find": "تلاش کرنا",
  "untouched": "نہ چھیڑا ہوا",
  "told": "بتایا",
  "speak": "بولنا", "says": "کہتا ہے", "said": "کہا", "tell": "بتانا", "tells": "بتاتا ہے",
 "ask": "پوچھنا", "asks": "پوچھتا ہے", "asked": "پوچھا",
  "answer": "جواب", "answers": "جوابات", "answered": "جواب دیا", "reply": "جواب دینا", "replies": "جوابات دینا", "replied": "جواب دیا",
  "question": "سوال", "questions": "سوالات", "questioned": "سوال کیا", "explain": "وضاحت کرنا", "explains": "وضاحت کرتا ہے", "explained": "وضاحت کی",
  "describe": "بیان کرنا", "describes": "بیان کرتا ہے",
  "chairman": "چیئرمین",
  "stated": "بیان کیا",
  "collaboration": "تعاون",
  "platform": "پلیٹ فارم",
  "expertise": "مہارت",
  "provide": "فراہم کرنا",
  "advance": "ترقی دینا",
  "build": "تعمیر کرنا",
  "group": "گروپ",
  "integration": "انضمام",
  "solution": "حل",
  "industry": "صنعت",
  "education": "تعلیم",
  "science": "سائنس",
  "international": "بین الاقوامی",
  "national": "قومی",
  "center": "مرکز",
  "centered": "مرکوز",
  "centerpiece": "مرکزی ٹکڑا",
  "centered around": "مرکز کے گرد",
  "centered on": "مرکز پر",
  "centered in": "مرکز میں",
  "centered at": "مرکز پر",
  "centered by": "مرکز کے ذریعے",
  "centered for": "مرکز کے لیے",
  "centered with": "مرکز کے ساتھ",
  "centered through": "مرکز کے ذریعے",
  };

  let lowerText = english.toLowerCase();

  for (const phrase in phraseDictionary) {
    const regex = new RegExp(`\\b${phrase}\\b`, 'gi');
    lowerText = lowerText.replace(regex, phraseDictionary[phrase]);
  }

  return lowerText
    .split(' ')
    .map((word) => wordDictionary[word] || word)
    .join(' ');
}
